export async function generatePrepDoc(
  accessToken: string, 
  eventTitle: string, 
  agendaText: string
): Promise<string | null> {
  try {
    // 1. Create a blank document
    const createRes = await fetch("https://docs.googleapis.com/v1/documents", {
      method: "POST",
      headers: { 
        Authorization: `Bearer ${accessToken}`, 
        "Content-Type": "application/json" 
      },
      body: JSON.stringify({ 
        title: `[AGENT ZERO PREP] - ${eventTitle}` 
      })
    });
    
    if (!createRes.ok) throw new Error("Failed to create document");
    
    const docData = await createRes.json();
    const documentId = docData.documentId;

    // 2. The Tactical Dossier Template
    const structuredDossier = `========================================================
AUTONOMOUS PREPARATION DOSSIER: ${eventTitle.toUpperCase()}
GENERATED BY: AGENT ZERO [SHADOW CHRONOS SYSTEM]
STATUS: ACTIVE MITIGATION
========================================================

[ 1. RAW CONTEXT & OBJECTIVE ]
${agendaText || "Dynamic sync to align on critical project deliverables and mitigate deadline decay."}

[ 2. STRATEGIC DISCUSSION POINTS ]
☐ Review current operational blockers and bottlenecks.
☐ Establish clear, non-negotiable timeline for remaining milestones.
☐ Identify missing dependencies from external stakeholders.
☐ Confirm final QA and deployment procedures.

[ 3. REQUIRED OUTCOMES (DO NOT LEAVE MEETING WITHOUT THESE) ]
1. A written, immutable record of who is doing what by when.
2. Hard confirmation on the final delivery date.
3. Identification of the single point of failure (SPOF) for this cycle.

[ 4. POST-MEETING ACTION PROTOCOL ]
- Immediately update the Agent Zero Memory Matrix with new constraints.
- Dispatch follow-up proxy emails to all attendees summarizing agreed-upon stakes.

========================================================
SYSTEM NOTE: Procrastination on these action items carries severe consequence multipliers. Maintain zero-trust posture regarding verbal commitments. Document everything.
========================================================`;

    // 3. Inject the massive dossier into the document
    await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
      method: "POST",
      headers: { 
        Authorization: `Bearer ${accessToken}`, 
        "Content-Type": "application/json" 
      },
      body: JSON.stringify({
        requests: [{
          insertText: {
            location: { index: 1 },
            text: structuredDossier
          }
        }]
      })
    });

    // Return the URL so we can attach it to the TaskCard
    return `https://docs.google.com/document/d/${documentId}/edit`;
    
  } catch (error) {
    console.error("Docs Generation Error:", error);
    return null;
  }
}